name: Test, Build and Deploy to aws
on:
  push:
    branches:
      - dev

jobs:
  execute_tests:
    name: execute tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: |
          pip install -r requirements.txt
          cd project
          python manage.py test

  setup-build-publish-deploy:
    name: pull repo and deploy
    runs-on: ubuntu-latest
    needs: [execute_tests]

    steps:
      - name: Build and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/work/project
            git pull origin dev
            sudo docker-compose up --build -d
